export const vaultedPrimeItems = new Set<string>([
  ...[
    // Warframes
    ...[
      "Ash",
      "Atlas",
      "Banshee",
      "Baruuk",
      "Chroma",
      "Ember",
      "Equinox",
      "Frost",
      "Gara",
      "Garuda",
      "Gauss",
      "Grendel",
      "Harrow",
      "Hildryn",
      "Hydroid",
      "Inaros",
      "Ivara",
      "Khora",
      "Limbo",
      "Loki",
      "Mag",
      "Mesa",
      "Mirage",
      "Nekros",
      "Nezha",
      "Nidus",
      "Nova",
      "Nyx",
      "Oberon",
      "Octavia",
      "Revenant",
      "Rhino",
      "Saryn",
      "Titania",
      "Trinity",
      "Vauban",
      "Volt",
      "Wisp",
      "Wukong",
      "Zephyr",
    ],
    // Primary
    ...[
      "Acceltra",
      "Astilla",
      "Baza",
      "Boar",
      "Boltor",
      "Corinth",
      "Fulmin",
      "Latron",
      "NAgantaka",
      "Panthera",
      "Phantasma",
      "Rubico",
      "Scourge",
      "Soma",
      "Stradavar",
      "Strun",
      "Sybaris",
      "Tenora",
      "Tiberon",
      "Tigris",
      "Vectis",
      "Zhuge",
    ],
    // Secondary
    ...[
      "Afuris",
      "Akarius",
      "Akbolto",
      "Akjagara",
      "Aksomati",
      "Akstiletto",
      "Ballistica",
      "Euphona",
      "Hystrix",
      "Knell",
      "Pandero",
      "Pyrana",
      "Sicarus",
      "Spira",
      "Vasto",
      "Zakti",
      "Zylok",
    ],
    // Melee
    ...[
      "Ankyros",
      "Bo",
      "Cobra & Crane",
      "Dakra",
      "Destreza",
      "Dual Kamas",
      "Dual Keres",
      "Fragor",
      "Galatine",
      "Glaive",
      "Gram",
      "Guandao",
      "Gunsen",
      "Karyst",
      "Kogake",
      "Kronen",
      "Masseter",
      "Nami Skyla",
      "Nikana",
      "Ninkondi",
      "Pangolin",
      "Reaper",
      "Redeemer",
      "Silva & Aegis",
      "Tatsu",
      "Tekko",
      "Tipedo",
      "Volnus",
    ],
    // Other
    ...[
      "Corvas",
      "Larkspur",
      "Carrier",
      "Dethcube",
      "Helios",
      "Shade",
      "Wyrm",
      "Kavasa Prime Collar",
      "Burst Laser",
      "Deconstructor",
      "Deth Machine Rifle",
      "Sweeper",
    ],
    ...["Odonata"],
  ].map((n) => n + " Prime"),
  "Prime Laser Rifle",
]);

export const primeResurgenceItems = new Set<string>(
  [
    ...["Ember", "Frost", "Glaive", "Latron", "Reaper", "Sicarus"],
    ...["Ash", "Inaros", "Karyst", "Panthera", "Vectis", "Carrier"],
    ...["Hydroid", "Mesa", "Akjagara", "Ballistica", "Nami Skyla", "Redeemer"],
    ...["Loki", "Volt", "Bo", "Wyrm", "Odonata"],
  ].map((n) => n + " Prime")
);
